name: Metrics

on:
  schedule: 
    - cron: "16 16 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}         # classic PAT
          committer_token: ${{ secrets.METRICS_TOKEN }}  # 用同一個 PAT commit
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
